Update solr_update_on_push.yml

diff --git a/.github/workflows/solr_update_on_push.yml b/.github/workflows/solr_update_on_push.yml
--- a/.github/workflows/solr_update_on_push.yml
+++ b/.github/workflows/solr_update_on_push.yml
@@ -23,17 +23,15 @@ jobs:
           lsb-release \
           curl
 
-    - name: Remove Conflicting Package
+    - name: Remove Conflicting Docker Packages
       run: |
         sudo apt-get remove -y containerd || true
         sudo apt-get purge -y containerd || true
         sudo apt-get autoremove -y
+        sudo apt-get install -y docker.io
 
-    - name: Set up Docker
-      run: |
-        sudo apt-get install -y \
-          docker.io \
-          containerd.io
+    - name: Start Docker Service
+      run: sudo systemctl start docker
 
     - name: Build and Run Solr Docker Container
       run: |
@@ -42,11 +40,24 @@ jobs:
       env:
         SOLR_URL: http://localhost:8983/solr/regolamento_1/update/json/docs
 
+    - name: Check Docker Container Status and Logs
+      run: |
+        # Check if the container is running
+        if [[ $(docker ps -q -f name=my-solr-container) ]]; then
+          echo "Solr container is running."
+        else
+          echo "Solr container failed to start."
+          exit 1
+        fi
+        # Output Solr container logs
+        docker logs my-solr-container
+        echo "Waiting for Solr to be ready..."
+
     - name: Wait for Solr to be Ready
       run: |
         # Wait until Solr responds to HTTP requests
         until $(curl --output /dev/null --silent --head --fail "$SOLR_URL"); do
-          echo "Waiting for Solr..."
+          echo "Waiting for Solr to be ready..."
           sleep 5
         done
         echo "Solr is ready."
